# 設置系統語言環境
language: node_js
# 是否需要 sudo 權限
sudo: false
# 設置node_js版本
node_js: "stable"
## 安裝 Hexo-Cli
before_script:
  - npm install hexo-cli -g  # 安裝 Hexo 環境
  - npm install --no-progress

# 清除緩存並執行編譯
script:
  - hexo clean
  - hexo generate
## deploy 相關設置
after_success:
  - sed -i'' "/^ *repo/s~github\.com~${GITHUBHEXO_TOKEN}@github.com~" _config.yml
  - hexo deploy
